/**
 * Cost Avoidance Service — Task 12.1
 * Business logic for tracking avoided costs through optimization actions.
 *
 * Cost avoidance = savings generated by proactive actions (rightsizing, reservations, deletions)
 * that prevented future spending.
 */

/**
 * Calculate total cost avoidance for a given period.
 * @param {Array<{estimatedSavingsUsd: number, actionDate: string}>} records
 * @returns {{totalUsd: number, totalCop: number, count: number}}
 */
const calculateTotalAvoidance = (records) => {
  const totalUsd = records.reduce((sum, r) => sum + r.estimatedSavingsUsd, 0);
  return {
    totalUsd: Math.round(totalUsd * 100) / 100,
    totalCop: Math.round(totalUsd * 4200 * 100) / 100,
    count: records.length,
  };
};

/**
 * Group cost avoidance by action type.
 * @param {Array<{actionType: string, estimatedSavingsUsd: number}>} records
 * @returns {Array<{actionType: string, totalUsd: number, totalCop: number, count: number}>}
 */
const groupByActionType = (records) => {
  const groups = {};

  for (const record of records) {
    if (!groups[record.actionType]) {
      groups[record.actionType] = { totalUsd: 0, count: 0 };
    }
    groups[record.actionType].totalUsd += record.estimatedSavingsUsd;
    groups[record.actionType].count += 1;
  }

  return Object.entries(groups)
    .map(([actionType, data]) => ({
      actionType,
      totalUsd: Math.round(data.totalUsd * 100) / 100,
      totalCop: Math.round(data.totalUsd * 4200 * 100) / 100,
      count: data.count,
    }))
    .sort((a, b) => b.totalUsd - a.totalUsd);
};

/**
 * Calculate monthly avoidance trend.
 * @param {Array<{actionDate: string, estimatedSavingsUsd: number}>} records
 * @returns {Array<{month: string, totalUsd: number, totalCop: number}>}
 */
const calculateMonthlyTrend = (records) => {
  const monthMap = {};

  for (const record of records) {
    const month = record.actionDate.slice(0, 7); // YYYY-MM
    if (!monthMap[month]) {
      monthMap[month] = 0;
    }
    monthMap[month] += record.estimatedSavingsUsd;
  }

  return Object.entries(monthMap)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([month, totalUsd]) => ({
      month,
      totalUsd: Math.round(totalUsd * 100) / 100,
      totalCop: Math.round(totalUsd * 4200 * 100) / 100,
    }));
};

module.exports = {
  calculateTotalAvoidance,
  groupByActionType,
  calculateMonthlyTrend,
};
